// GENERATED by scripts/embed-migrations.ts — do not edit.
//
// An import manifest, not a copy: each migration is imported as text so the bundler
// compiles it into the binary, while drizzle/ remains the only place the SQL lives.
// Regenerate with `bun run db:generate`; the build regenerates too, so a binary cannot
// ship a manifest that disagrees with the folder.

import journalJson from "../../drizzle/meta/_journal.json" with { type: "json" };
import m0000EminentSteelSerpent from "../../drizzle/0000_eminent_steel_serpent.sql" with { type: "text" };
import m0001OutstandingSharonVentura from "../../drizzle/0001_outstanding_sharon_ventura.sql" with { type: "text" };
import m0002CulturedMicrobe from "../../drizzle/0002_cultured_microbe.sql" with { type: "text" };
import m0003TalentedJigsaw from "../../drizzle/0003_talented_jigsaw.sql" with { type: "text" };
import m0004ThirdMorlun from "../../drizzle/0004_third_morlun.sql" with { type: "text" };
import m0005PreviousGoliath from "../../drizzle/0005_previous_goliath.sql" with { type: "text" };
import m0006CommonZemo from "../../drizzle/0006_common_zemo.sql" with { type: "text" };
import m0007DailyHumanCannonball from "../../drizzle/0007_daily_human_cannonball.sql" with { type: "text" };
import m0008DryBullseye from "../../drizzle/0008_dry_bullseye.sql" with { type: "text" };
import m0009OpenMode from "../../drizzle/0009_open_mode.sql" with { type: "text" };
import m0010NarrowAnthem from "../../drizzle/0010_narrow_anthem.sql" with { type: "text" };
import m0011KeenBrood from "../../drizzle/0011_keen_brood.sql" with { type: "text" };
import m0012LameRobbieRobertson from "../../drizzle/0012_lame_robbie_robertson.sql" with { type: "text" };
import m0013MassiveCammi from "../../drizzle/0013_massive_cammi.sql" with { type: "text" };
import m0014RedundantWhizzer from "../../drizzle/0014_redundant_whizzer.sql" with { type: "text" };
import m0015FreezingSteveRogers from "../../drizzle/0015_freezing_steve_rogers.sql" with { type: "text" };

export interface EmbeddedMigrations {
  journal: string;
  files: Record<string, string>;
}

const files: Record<string, string> = {
  "0000_eminent_steel_serpent.sql": m0000EminentSteelSerpent,
  "0001_outstanding_sharon_ventura.sql": m0001OutstandingSharonVentura,
  "0002_cultured_microbe.sql": m0002CulturedMicrobe,
  "0003_talented_jigsaw.sql": m0003TalentedJigsaw,
  "0004_third_morlun.sql": m0004ThirdMorlun,
  "0005_previous_goliath.sql": m0005PreviousGoliath,
  "0006_common_zemo.sql": m0006CommonZemo,
  "0007_daily_human_cannonball.sql": m0007DailyHumanCannonball,
  "0008_dry_bullseye.sql": m0008DryBullseye,
  "0009_open_mode.sql": m0009OpenMode,
  "0010_narrow_anthem.sql": m0010NarrowAnthem,
  "0011_keen_brood.sql": m0011KeenBrood,
  "0012_lame_robbie_robertson.sql": m0012LameRobbieRobertson,
  "0013_massive_cammi.sql": m0013MassiveCammi,
  "0014_redundant_whizzer.sql": m0014RedundantWhizzer,
  "0015_freezing_steve_rogers.sql": m0015FreezingSteveRogers,
};

export const embeddedMigrations: EmbeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

/** Number of migrations compiled in, for the startup sanity check. */
export const embeddedMigrationCount: number = Object.keys(files).length;
