/**
 * Generate src/db/migrations-embedded.ts — an import manifest for the drizzle/ folder.
 *
 * The migrator reads SQL from disk at runtime. That works from a source checkout, where
 * ./drizzle sits in the working directory, and fails for a compiled binary: it is a single
 * file installed to /usr/local/bin and the service runs with
 * WorkingDirectory=/var/lib/anpan-os, where no drizzle/ folder exists. A fresh install
 * therefore created *no tables at all*, reported as "No migration files found".
 *
 * The generated file imports each .sql with `type: "text"`, which the bundler resolves and
 * compiles into the binary — verified by deleting the .sql files and running the binary
 * from an unrelated directory. The SQL itself is never copied: drizzle/ stays the single
 * source, and this manifest is only a list of imports, so a new migration produces a
 * one-line diff rather than a duplicated file.
 *
 * Run by `bun run db:generate` and by the build, so the manifest cannot drift from the
 * folder it mirrors.
 */

import { readdir } from "node:fs/promises";
import { join } from "node:path";

const DRIZZLE_DIR = "drizzle";
const OUT_PATH    = "src/db/migrations-embedded.ts";

interface JournalEntry { idx: number; version: string; when: number; tag: string; breakpoints: boolean }
interface Journal { version: string; dialect: string; entries: JournalEntry[] }

const journal = await Bun.file(join(DRIZZLE_DIR, "meta", "_journal.json")).json() as Journal;
const sqlFiles = (await readdir(DRIZZLE_DIR)).filter(f => f.endsWith(".sql")).sort();

// An empty journal would satisfy both checks below and emit a valid but empty manifest,
// so the build would succeed and the binary would exit at startup instead. A project with
// no migrations cannot create its schema, and that is a generation-time fault.
if (journal.entries.length === 0) {
  console.error(`✖ ${DRIZZLE_DIR}/meta/_journal.json lists no migrations — run drizzle-kit generate`);
  process.exit(1);
}

// Journal and folder must agree in both directions, or the binary ships a manifest
// describing migrations it cannot run — or silently omits ones it should.
const missing = journal.entries.map(e => `${e.tag}.sql`).filter(n => !sqlFiles.includes(n));
if (missing.length > 0) {
  console.error(`✖ journal names ${missing.join(", ")}, absent from ${DRIZZLE_DIR}/`);
  process.exit(1);
}
const orphans = sqlFiles.filter(n => !journal.entries.some(e => `${e.tag}.sql` === n));
if (orphans.length > 0) {
  console.error(`✖ ${orphans.join(", ")} present but not in the journal — run drizzle-kit generate`);
  process.exit(1);
}

// Drizzle resumes by comparing against the newest recorded timestamp, so equal or
// decreasing `when` values make it skip a migration silently. Catch that here, where the
// fix is to regenerate, rather than at a user's first boot.
for (let i = 1; i < journal.entries.length; i++) {
  const prev = journal.entries[i - 1]!;
  const curr = journal.entries[i]!;
  if (curr.when <= prev.when) {
    console.error(`✖ ${curr.tag} (${curr.when}) is not after ${prev.tag} (${prev.when}) — Drizzle would skip a migration`);
    process.exit(1);
  }
}

/** `0014_redundant_whizzer` → `m0014RedundantWhizzer`, a valid identifier. */
const ident = (tag: string) =>
  "m" + tag.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) => (c ? c.toUpperCase() : ""));

const imports = journal.entries
  .map(e => `import ${ident(e.tag)} from "../../${DRIZZLE_DIR}/${e.tag}.sql" with { type: "text" };`)
  .join("\n");

const entries = journal.entries
  .map(e => `  ${JSON.stringify(`${e.tag}.sql`)}: ${ident(e.tag)},`)
  .join("\n");

const body = `// GENERATED by scripts/embed-migrations.ts — do not edit.
//
// An import manifest, not a copy: each migration is imported as text so the bundler
// compiles it into the binary, while drizzle/ remains the only place the SQL lives.
// Regenerate with \`bun run db:generate\`; the build regenerates too, so a binary cannot
// ship a manifest that disagrees with the folder.

import journalJson from "../../${DRIZZLE_DIR}/meta/_journal.json" with { type: "json" };
${imports}

export interface EmbeddedMigrations {
  journal: string;
  files: Record<string, string>;
}

const files: Record<string, string> = {
${entries}
};

export const embeddedMigrations: EmbeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

/** Number of migrations compiled in, for the startup sanity check. */
export const embeddedMigrationCount: number = Object.keys(files).length;
`;

await Bun.write(OUT_PATH, body);
console.log(`✅ manifest for ${journal.entries.length} migrations → ${OUT_PATH}`);
